# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnclosedParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('total_capacity', models.PositiveIntegerField()),
                ('number_of_filled_spots', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='enclosedparkinglot',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ParkingGroup'),
        ),
    ]
