# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 05:54
from __future__ import unicode_literals

from django.db import migrations


APP_NAME = "main_app"


# create some dummy parking lots
def add_lots(apps, schema_editor):

	EnclosedParkingLot = apps.get_model(APP_NAME, "EnclosedParkingLot")
	ParkingGroup = apps.get_model(APP_NAME, "ParkingGroup")

	group = ParkingGroup.objects.create(
		name="Texas A&M Kingsville-University",
	)

	EnclosedParkingLot.objects.create(
		name="Engineering Complex",
		group=group,
		number=0,
		total_capacity=150,
	)

	EnclosedParkingLot.objects.create(
		name="MSUB",
		group=group,
		number=1,
		total_capacity=64,
	)

	EnclosedParkingLot.objects.create(
		name="Business Administration Building",
		group=group,
		number=2,
		total_capacity=118,
	)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(add_lots),
    ]
